---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/BaseBeyond/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/assets
    - /bin/cp -R assets $DEPLOYPATH
