import React, { Suspense, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { Float, MeshTransmissionMaterial, Sparkles } from '@react-three/drei';
import * as THREE from 'three';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import Lenis from 'lenis';
import { motion, AnimatePresence, useMotionValue, useSpring } from 'motion/react';
import { ArrowDownRight, ArrowRight, Asterisk, Blocks, Bot, Check, ExternalLink, Globe2, Menu, MousePointer2, MoveUpRight, Plus, Quote, Sparkles as SparklesIcon, X, Zap } from 'lucide-react';
import './styles.css';
gsap.registerPlugin(ScrollTrigger);
const services=[{index:'01',title:'Web experiences',copy:'Brand-first websites with cinematic motion, responsive storytelling and conversion-aware structure.',icon:Globe2,meta:'DESIGN · 3D · MOTION'},{index:'02',title:'Digital systems',copy:'Portals, dashboards, CRMs and custom tools shaped around the way your team actually works.',icon:Blocks,meta:'APPS · CRM · PORTALS'},{index:'03',title:'Automation',copy:'Remove repetitive work with smart workflows, integrations, agents and intelligent operations.',icon:Bot,meta:'AI · API · WORKFLOWS'},{index:'04',title:'Growth layer',copy:'SEO foundations, analytics, experiments and ongoing iteration after launch — not a handoff and goodbye.',icon:Zap,meta:'SEO · DATA · CARE'}];
const work=[
{id:'01',title:'KBoom',type:'Cleaning service platform',stat:'LIVE',label:'quote + operations',hue:'violet',summary:'A premium service website with an interactive customer quote estimator and owner-side pricing controls.',features:['Instant quote estimator','Owner pricing controls','Premium responsive service experience'],stack:'React · UI Systems · Business Logic'},
{id:'02',title:'TripFlow',type:'Travel operating system',stat:'PWA',label:'travel workspace',hue:'lime',summary:'A connected travel workspace for itinerary planning, budgets, reservations, documents, maps and trip readiness.',features:['Itinerary + calendar','Budget + expense splitting','Reservations + document vault'],stack:'PWA · PHP · SQLite · APIs'},
{id:'03',title:'SecureLink Tech',type:'Field operations platform',stat:'OPS',label:'portal ecosystem',hue:'ice',summary:'A multi-role operations system for technicians, owners and admins with earnings, invoices and workflow automation.',features:['Technician / owner / admin portals','Invoice + earnings workflows','Operational automation'],stack:'PHP · SQLite · Automation · Integrations'}
];
const buildPlans=[
{name:'Launch',price:'599',tag:'START HERE',copy:'A sharp, professional presence for a new or growing business.',features:['Up to 5 pages','Mobile responsive design','Contact / quote form','Basic SEO setup','Google Maps + social links','Launch support']},
{name:'Growth',price:'999',tag:'MOST POPULAR',copy:'More pages, stronger conversion structure and a better foundation for growth.',features:['Up to 10 pages','Everything in Launch','Individual service pages','Google Analytics setup','Enhanced SEO structure','Testimonials + conversion design']},
{name:'Beyond',price:'1,499+',tag:'PREMIUM',copy:'A custom digital experience with advanced functionality and room to scale.',features:['Up to 15 pages','Everything in Growth','Custom design direction','Optional online booking','CRM + automation setup','Lead tracking + advanced integrations']}
];
const carePlans=[
{name:'Essential',price:'49',copy:'Keep the website fast, secure and looked after.',features:['Hosting + SSL','Backups + security monitoring','Software updates','15 minutes minor edits / month']},
{name:'Growth Care',price:'99',copy:'Ongoing content, SEO and performance support.',features:['Everything in Essential','1 hour edits / month','Basic on-page SEO','Monthly performance report']},
{name:'Pro',price:'199',copy:'For businesses that need their website connected to sales operations.',features:['Everything in Growth Care','CRM + lead tracking','Automated follow-ups','2 hours edits / month']},
{name:'AI Growth',price:'299',copy:'Automated lead response and recovery for high-intent enquiries.',features:['Everything in Pro','AI website assistant','SMS + email follow-up','Missed-lead recovery']}
];
function useReducedMotionPref(){const[r,setR]=useState(false);useEffect(()=>{const m=matchMedia('(prefers-reduced-motion: reduce)');const s=()=>setR(m.matches);s();m.addEventListener?.('change',s);return()=>m.removeEventListener?.('change',s)},[]);return r}
function SmoothScroll(){const r=useReducedMotionPref();useEffect(()=>{if(r)return;const l=new Lenis({duration:1.05,smoothWheel:true,wheelMultiplier:.85});l.on('scroll',ScrollTrigger.update);const u=t=>l.raf(t*1000);gsap.ticker.add(u);gsap.ticker.lagSmoothing(0);return()=>{gsap.ticker.remove(u);l.destroy()}},[r]);return null}
function CursorAura(){const x=useMotionValue(-200),y=useMotionValue(-200),sx=useSpring(x,{stiffness:260,damping:28,mass:.35}),sy=useSpring(y,{stiffness:260,damping:28,mass:.35});useEffect(()=>{const m=e=>{x.set(e.clientX);y.set(e.clientY)};addEventListener('pointermove',m,{passive:true});return()=>removeEventListener('pointermove',m)},[]);return <motion.div aria-hidden className="cursor-aura" style={{x:sx,y:sy}}/>}
function Magnetic({children,className=''}){const ref=useRef(),reduced=useReducedMotionPref();const move=e=>{if(reduced||!ref.current)return;const r=ref.current.getBoundingClientRect();gsap.to(ref.current,{x:(e.clientX-r.left-r.width/2)*.18,y:(e.clientY-r.top-r.height/2)*.18,duration:.35,ease:'power3.out'})};return <span ref={ref} className={'magnetic '+className} onPointerMove={move} onPointerLeave={()=>gsap.to(ref.current,{x:0,y:0,duration:.65,ease:'elastic.out(1,.45)'})}>{children}</span>}
function MotionSystem(){const reduced=useReducedMotionPref();useEffect(()=>{if(reduced)return;const ctx=gsap.context(()=>{
gsap.utils.toArray('.reveal').forEach(el=>gsap.fromTo(el,{y:55,opacity:0,rotateX:8},{y:0,opacity:1,rotateX:0,duration:1,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 88%',once:true}}));
gsap.utils.toArray('[data-parallax]').forEach(el=>gsap.to(el,{yPercent:Number(el.dataset.parallax||-12),ease:'none',scrollTrigger:{trigger:el.parentElement,start:'top bottom',end:'bottom top',scrub:1}}));
gsap.utils.toArray('.pricing-orb,.contact-bg-text').forEach(el=>gsap.to(el,{yPercent:-18,rotate:4,ease:'none',scrollTrigger:{trigger:el.parentElement,start:'top bottom',end:'bottom top',scrub:1.2}}));
});return()=>ctx.revert()},[reduced]);return null}
function TiltCard({children,className=''}){const ref=useRef();const reduced=useReducedMotionPref();const move=e=>{if(reduced||!ref.current)return;const r=ref.current.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;ref.current.style.setProperty('--mx',x*100+'%');ref.current.style.setProperty('--my',y*100+'%');gsap.to(ref.current,{rotateY:(x-.5)*7,rotateX:(.5-y)*7,y:-4,duration:.35,ease:'power2.out'})};const leave=()=>ref.current&&gsap.to(ref.current,{rotateX:0,rotateY:0,y:0,duration:.7,ease:'elastic.out(1,.5)'});return <div ref={ref} className={'tilt-card '+className} onPointerMove={move} onPointerLeave={leave}>{children}</div>}
function SceneRig(){const group=useRef(),core=useRef();const{pointer,viewport}=useThree();useFrame((_,d)=>{if(!group.current)return;group.current.rotation.y=THREE.MathUtils.damp(group.current.rotation.y,pointer.x*.42,4,d);group.current.rotation.x=THREE.MathUtils.damp(group.current.rotation.x,-pointer.y*.26,4,d);group.current.position.x=THREE.MathUtils.damp(group.current.position.x,pointer.x*viewport.width*.018,3,d);core.current.rotation.x+=d*.11;core.current.rotation.y-=d*.08});return <group ref={group}><Float speed={1.25} floatIntensity={.55} rotationIntensity={.35}><mesh ref={core} scale={1.22} rotation={[.45,.45,0]}><torusKnotGeometry args={[1.25,.34,180,24,2,3]}/><MeshTransmissionMaterial transmission={1} thickness={.68} roughness={.12} ior={1.35} chromaticAberration={.12} anisotropy={.3} distortion={.25} distortionScale={.28} temporalDistortion={.1} clearcoat={1} color="#dfff86"/></mesh></Float><mesh rotation={[Math.PI/2,0,0]} scale={2.55}><torusGeometry args={[1.1,.012,8,180]}/><meshBasicMaterial color="#dfff86" transparent opacity={.45}/></mesh><mesh rotation={[Math.PI/2.45,.2,.8]} scale={3.2}><torusGeometry args={[1.1,.008,8,180]}/><meshBasicMaterial color="#b89aff" transparent opacity={.22}/></mesh><Sparkles count={90} scale={7} size={1.25} speed={.2} opacity={.42} color="#f3f3e9"/></group>}
function HeroCanvas(){return <div className="hero-canvas" aria-hidden><Canvas camera={{position:[0,0,5.8],fov:48}} dpr={[1,1.65]} gl={{antialias:true,alpha:true,powerPreference:'high-performance'}}><ambientLight intensity={1.4}/><directionalLight position={[3,4,5]} intensity={4.5} color="#e9ffc0"/><pointLight position={[-3,-1,2]} intensity={18} color="#8a6cff"/><Suspense fallback={null}><SceneRig/></Suspense></Canvas></div>}
function Navbar({menu,setMenu}){return <header className="nav-shell"><a className="brand" href="#top"><span className="brand-mark"><span/></span><span>BASE <i>&</i> BEYOND</span></a><nav className="desktop-nav"><a href="#work">Work</a><a href="#services">Capabilities</a><a href="#process">Process</a><a href="#pricing">Pricing</a><a href="#contact">Contact</a></nav><Magnetic><a className="nav-cta" href="#contact">Start a project <ArrowDownRight size={15}/></a></Magnetic><button className="menu-btn" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>}
function MobileMenu({open,setOpen}){return <AnimatePresence>{open&&<motion.div className="mobile-menu" initial={{clipPath:'circle(0% at 92% 5%)'}} animate={{clipPath:'circle(150% at 92% 5%)'}} exit={{clipPath:'circle(0% at 92% 5%)'}} transition={{duration:.65,ease:[.76,0,.24,1]}}><div className="mobile-menu-links">{[['Work','work'],['Capabilities','services'],['Process','process'],['Pricing','pricing'],['Contact','contact']].map(([t,id],i)=><motion.a key={id} href={'#'+id} onClick={()=>setOpen(false)} initial={{y:40,opacity:0}} animate={{y:0,opacity:1}} transition={{delay:.18+i*.06}}>{t}<span>0{i+1}</span></motion.a>)}</div></motion.div>}</AnimatePresence>}
function Hero(){const root=useRef();useEffect(()=>{const c=gsap.context(()=>{gsap.from('.hero-kicker > *',{y:22,opacity:0,stagger:.06,duration:.8});gsap.from('.hero-word',{yPercent:115,rotateX:-35,stagger:.09,duration:1.15,ease:'expo.out',delay:.15});gsap.from('.hero-support',{y:28,opacity:0,duration:.9,delay:.6});gsap.to('.hero-content',{y:-100,opacity:.45,scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1.2}});gsap.to('.hero-canvas',{y:120,scale:.86,opacity:.35,scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1.1}})},root);return()=>c.revert()},[]);return <section id="top" className="hero" ref={root}><div className="hero-grid"/><HeroCanvas/><div className="hero-content container"><div className="hero-kicker"><span><Asterisk size={15}/> INDEPENDENT DIGITAL STUDIO</span><span>CANADA · WORLDWIDE</span></div><h1><span className="line"><span className="hero-word thin">BUILT FROM</span></span><span className="line offset"><span className="hero-word solid">BASE.</span></span><span className="line"><span className="hero-word thin">TAKEN</span><span className="hero-word accent">BEYOND.</span></span></h1><div className="hero-support"><div className="hero-copy"><p>Websites should not feel assembled.</p><p>They should feel <strong>directed.</strong></p></div><Magnetic><a href="#work" className="orb-btn"><span>Explore our world</span><ArrowDownRight/><i/></a></Magnetic></div></div><div className="hero-bottom"><span>SCROLL TO ENTER</span><div className="scroll-line"><i/></div><span>©26 — B&B</span></div></section>}
function Manifesto(){return <section className="manifesto"><div className="container manifesto-wrap"><span className="eyebrow">/ OUR POINT OF VIEW</span><div className="manifesto-copy reveal"><div>Most websites explain.</div><div>The memorable ones <em>move you.</em></div><div>We combine strategy, interface,</div><div>code and motion into digital</div><div>experiences with a pulse.</div></div><div className="manifesto-foot"><span>01 / STRATEGY</span><span>02 / DESIGN</span><span>03 / MOTION</span><span>04 / BUILD</span></div></div></section>}
function WorkCard({item,onOpen}){const ref=useRef(),[hover,setHover]=useState(false);return <article ref={ref} className={'work-card '+item.hue} onPointerEnter={()=>setHover(true)} onPointerLeave={()=>setHover(false)}><div className="card-mesh"/><div className="work-head"><span>{item.id}</span><span>{item.type}</span></div><div className="work-stage"><motion.div className="device" animate={{rotateX:hover?-4:2,rotateY:hover?7:-4,y:hover?-9:0}}><div className="device-top"><i/><i/><i/></div><div className="device-screen"><div className="mini-nav"><b>{item.title==='SecureLink Tech'?'SL':item.title==='TripFlow'?'TF':'KB'}</b><span/><span/><span/></div><div className="mini-hero"><i/><strong>{item.title}</strong><small>{item.type.toUpperCase()}</small></div><div className="mini-grid"><span/><span/><span/></div></div></motion.div><div className="floating-chip chip-a"><MousePointer2 size={13}/> real project</div><div className="floating-chip chip-b"><SparklesIcon size={13}/> built by us</div></div><div className="work-foot"><div><h3>{item.title}</h3><p>{item.stack}</p></div><div className="work-stat"><strong>{item.stat}</strong><span>{item.label}</span></div><button type="button" onClick={()=>onOpen(item)} aria-label={'View '+item.title+' project details'}><MoveUpRight/></button></div></article>}
function ProjectModal({item,onClose}){useEffect(()=>{if(!item)return;const onKey=e=>e.key==='Escape'&&onClose();document.body.style.overflow='hidden';addEventListener('keydown',onKey);return()=>{document.body.style.overflow='';removeEventListener('keydown',onKey)}},[item,onClose]);return <AnimatePresence>{item&&<motion.div className="project-modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={e=>e.target===e.currentTarget&&onClose()}><motion.div className="project-modal" initial={{y:50,opacity:0,scale:.97}} animate={{y:0,opacity:1,scale:1}} exit={{y:30,opacity:0,scale:.98}} transition={{duration:.35,ease:[.2,.8,.2,1]}}><button className="modal-close" type="button" onClick={onClose} aria-label="Close project details"><X/></button><span className="eyebrow">/ PROJECT {item.id}</span><div className="modal-title-row"><h3>{item.title}</h3><span>{item.type}</span></div><p className="modal-summary">{item.summary}</p><div className="modal-features">{item.features.map((f,i)=><div key={f}><span>0{i+1}</span><strong>{f}</strong></div>)}</div><div className="modal-stack"><span>BUILT WITH</span><strong>{item.stack}</strong></div><a href="#contact" className="modal-cta" onClick={onClose}>Build something like this <ArrowRight/></a></motion.div></motion.div>}</AnimatePresence>}
function Work(){const[selected,setSelected]=useState(null);return <section id="work" className="work-section"><div className="container"><div className="section-top reveal"><div><span className="eyebrow">/ SELECTED WORK</span><h2>Proof of <em>difference.</em></h2></div><p>Real products and operational systems we have designed and built — from customer-facing experiences to full internal platforms.</p></div><div className="work-grid">{work.map(x=><WorkCard key={x.id} item={x} onOpen={setSelected}/>)}</div></div><ProjectModal item={selected} onClose={()=>setSelected(null)}/></section>}
function Services(){const tech=['HTML5','CSS3','JAVASCRIPT','TYPESCRIPT','PHP','SQL','PYTHON','NODE.JS','REACT','NEXT.JS','THREE.JS','WEBGL','GSAP','VITE','MYSQL','SQLITE','REST API','GITHUB','CLOUDFLARE','CPANEL','HTML5','CSS3','JAVASCRIPT','PHP'];return <section id="services" className="services-section"><div className="container"><div className="services-title reveal"><span className="eyebrow">/ CAPABILITIES</span><h2>Not a website.<br/><span>A digital advantage.</span></h2></div><div className="services-list">{services.map(s=>{const Icon=s.icon;return <a className="service-row" href={'#contact'} key={s.index} aria-label={'Discuss '+s.title}><div className="service-index">{s.index}</div><div className="service-title"><Icon/><h3>{s.title}</h3></div><p>{s.copy}</p><span className="service-meta">{s.meta}</span><div className="service-arrow"><ArrowRight/></div></a>})}</div><div className="tech-marquee" aria-label="Technology stack"><div>{tech.map((x,i)=><React.Fragment key={i}><span>{x}</span><Asterisk/></React.Fragment>)}</div></div></div></section>}
function Process(){const steps=[['01','Find the signal','We strip the noise away: your offer, audience, competition and the one idea the whole experience should communicate.'],['02','Build the world','Art direction, interface systems, motion language, 3D studies and prototypes — designed as one connected experience.'],['03','Engineer the feel','Responsive development, accessibility, performance and interactions are built together rather than bolted on later.'],['04','Launch & evolve','Analytics, refinements, care and experiments keep the experience improving after it meets the real world.']];return <section id="process" className="process-section"><div className="container process-grid"><div className="process-sticky reveal"><span className="eyebrow">/ HOW WE WORK</span><h2>Clarity first.<br/>Then <em>wonder.</em></h2><p>A disciplined process underneath the visual madness. Every movement has a reason. Every effect earns its pixels.</p><div className="process-disc"><span>B+</span></div></div><div className="process-steps">{steps.map(([n,t,c])=><article key={n}><div className="step-top"><span>{n}</span><Plus/></div><h3>{t}</h3><p>{c}</p></article>)}</div></div></section>}
function Pricing(){return <section id="pricing" className="pricing-section"><div className="pricing-grid-bg"/><div className="container"><div className="pricing-intro reveal"><span className="eyebrow">/ INVESTMENT</span><div><h2>Start at <em>$599.</em><br/>Grow when you’re ready.</h2><p>Clear one-time website pricing, then optional monthly care. No mystery retainers and no forced domain lock-in.</p></div></div><div className="pricing-group"><div className="pricing-group-head reveal"><span>01</span><h3>Website builds</h3><p>One-time project investment · CAD</p></div><div className="build-plan-grid">{buildPlans.map((plan,i)=><TiltCard key={plan.name} className={'plan-card build-plan '+(i===1?'featured':'')}><div className="plan-glow"/><div className="plan-top"><span>{plan.tag}</span><small>0{i+1}</small></div><h4>{plan.name}</h4><div className="plan-price"><sup>$</sup><strong>{plan.price}</strong><small>CAD</small></div><p>{plan.copy}</p><div className="plan-features">{plan.features.map(f=><span key={f}><Check/> {f}</span>)}</div><Magnetic><a href="#contact" className="plan-cta">Choose {plan.name}<ArrowRight/></a></Magnetic></TiltCard>)}</div><div className="pricing-note reveal"><span>PAYMENT</span><strong>50% upfront · 50% on approval</strong><span>DOMAIN</span><strong>Registered separately and client-owned · typically $15–30/year</strong></div></div><div className="pricing-group care-group"><div className="pricing-group-head reveal"><span>02</span><h3>Monthly care</h3><p>Optional ongoing support · cancel or change as your needs evolve</p></div><div className="care-plan-grid">{carePlans.map((plan,i)=><TiltCard key={plan.name} className={'plan-card care-plan '+(i===1?'featured-care':'')}><div className="plan-top"><span>{i===1?'POPULAR':'CARE'}</span><small>0{i+1}</small></div><h4>{plan.name}</h4><div className="plan-price compact"><sup>$</sup><strong>{plan.price}</strong><small>/ month</small></div><p>{plan.copy}</p><div className="plan-features">{plan.features.map(f=><span key={f}><Check/> {f}</span>)}</div><a href="#contact" className="care-cta">Add monthly care <ArrowRight/></a></TiltCard>)}</div></div></div></section>}
function Contact(){const[copied,setCopied]=useState(false);return <section id="contact" className="contact-section"><div className="contact-bg-text">BEYOND</div><div className="container contact-wrap"><div className="contact-kicker"><span><i/> AVAILABLE FOR SELECT PROJECTS</span><span>2026 — 2027</span></div><h2><span>HAVE A BASE?</span><br/><em>LET'S GO BEYOND.</em></h2><div className="contact-actions"><Magnetic><a href="mailto:hello@baseandbeyond.ca" className="contact-primary">Start a project <ArrowDownRight/></a></Magnetic><button className="copy-mail" onClick={async()=>{try{await navigator.clipboard.writeText('hello@baseandbeyond.ca');setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{}}}>{copied?'Copied':'hello@baseandbeyond.ca'} <span>{copied?<Check size={15}/>:<ExternalLink size={15}/>}</span></button></div><footer><a className="brand" href="#top"><span className="brand-mark"><span/></span><span>BASE <i>&</i> BEYOND</span></a><div className="footer-links"><a href="#work">Work</a><a href="#services">Capabilities</a><a href="#process">Process</a><a href="#pricing">Pricing</a></div><div className="footer-meta"><span>CANADA · WORLDWIDE</span><span>© 2026 BASE & BEYOND</span></div></footer></div></section>}
function Loader(){const[done,setDone]=useState(false);useEffect(()=>{const t=setTimeout(()=>setDone(true),1550);return()=>clearTimeout(t)},[]);return <AnimatePresence>{!done&&<motion.div className="loader" exit={{y:'-100%'}} transition={{duration:.8,ease:[.76,0,.24,1]}}><div className="loader-logo"><span>B</span><i>+</i><span>B</span></div><div className="loader-track"><motion.i initial={{scaleX:0}} animate={{scaleX:1}} transition={{duration:1.15}}/></div><motion.span initial={{opacity:0}} animate={{opacity:1}}>BUILDING BEYOND ORDINARY</motion.span></motion.div>}</AnimatePresence>}
function App(){const[menu,setMenu]=useState(false);return <><SmoothScroll/><MotionSystem/><Loader/><div className="noise"/><CursorAura/><Navbar menu={menu} setMenu={setMenu}/><MobileMenu open={menu} setOpen={setMenu}/><main><Hero/><Manifesto/><Work/><Services/><Process/><Pricing/><section className="quote-section"><div className="container quote-wrap"><Quote/><blockquote>“The goal isn't to make people say <em>nice website.</em> The goal is to make the brand impossible to confuse with anyone else.”</blockquote></div></section><Contact/></main></>}
createRoot(document.getElementById('root')).render(<App/>);